[package]
name = "flt"
version = "0.1"
lean_version = "leanprover-community/lean:3.50.3"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "4601791ea62fea875b488dafc4e6dede19e8363f"}
ModularForms = {git = "https://github.com/CBirkbeck/ModularForms", rev = "485be39051a18198eb89764e5c43990386717e20"}
