[package]
name = "flt"
version = "0.1"
lean_version = "leanprover-community/lean:3.30.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "1f566bcf7999356255f0e423253d5b5c7159a89a"}
